program/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.views.generic import RedirectView

from .views import (
    debug_og_image_for_talk,
    debug_og_image_for_workshop,
    schedule_day,
    schedule_json,
    schedule_redirect,
    session_detail,
    talks_list,
    workshops_list,
)

app_name = "program"

urlpatterns = [
    re_path("^$", RedirectView.as_view(pattern_name="program:talks_list")),
    re_path("^talks/$", talks_list, name="talks_list"),
    re_path("^workshops/$", workshops_list, name="workshops_list"),
    re_path(
        "^(?P<type>(talk|workshop|sprint|panel))s/(?P<session_id>\\d+)/$",
        session_detail,
        name="session_detail",
    ),
    # Schedule
    path("schedule/", schedule_redirect, name="schedule_redirect"),
    path("schedule/<str:conference_day>/", schedule_day, name="schedule_day"),
    path("schedule.json", schedule_json, name="schedule_json"),
]

# Routes for previewing OG images template.
# Activated only in DEBUG mode.
if settings.DEBUG:
    urlpatterns += [
        path("og-image/talks/<int:session_id>/", debug_og_image_for_talk),
        path("og-image/panels/<int:session_id>/", debug_og_image_for_talk),
        path("og-image/workshops/<int:session_id>/", debug_og_image_for_workshop),
        path("og-image/sprints/<int:session_id>/", debug_og_image_for_workshop),
    ]

urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path(
        "2023/",
        include(
            [
                path("", TemplateView.as_view(template_name='pages/homepage.html'), name='homepage'),
                path("coc/", TemplateView.as_view(template_name='pages/coc.html'), name='coc'),
                path("privacy-policy/", TemplateView.as_view(template_name='pages/privacy_policy.html'), name='privacy_policy'),
                path("cfp/", TemplateView.as_view(template_name='pages/cfp.html'), name='cfp'),
                path("cfp-guide/", TemplateView.as_view(template_name='pages/cfp_guide.html'), name='cfp_guide'),
                path("cfp-pruvodce/", TemplateView.as_view(template_name='pages/cfp_pruvodce.html'), name='cfp_pruvodce'),
                path("sponsorship/", TemplateView.as_view(template_name='pages/sponsorship.html'), name='sponsorship'),
                # Original view for tickets: TemplateView.as_view(template_name='pages/tickets.html')
                path("tickets/", RedirectView.as_view(pattern_name="homepage"), name='tickets'),
                path("financial-aid/", TemplateView.as_view(template_name='pages/financial-aid.html'), name='financial_aid'),
                path("financial-aid-grantees/", TemplateView.as_view(template_name='pages/financial-aid-grantees.html'), name='financial_aid_grantees'),
                path("venue/", TemplateView.as_view(template_name='pages/venue.html'), name='venue'),
                path("board-game-night/", TemplateView.as_view(template_name='pages/board-game-night.html'), name='board_game_night'),
                path("prague/", TemplateView.as_view(template_name='pages/prague.html'), name='prague'),

                path("pyconcz-discord/", RedirectView.as_view(url='https://discord.gg/UtPkpPB7te', permanent=True)),
                path("discord/", RedirectView.as_view(url='https://discord.gg/UtPkpPB7te', permanent=True)),
                path("3D/", RedirectView.as_view(url='https://docs.google.com/forms/d/e/1FAIpQLSeyr13vobeJVqBgucq27j0yLzbH6tTmSYP4dZEDLEkCYHI6Hg/viewform', permanent=True)),
                path("tshirt/", RedirectView.as_view(url='https://pretix.eu/pyconcz/pyconcz23/redeem?voucher=TSHIRT', permanent=False)),
                path("schedule/", RedirectView.as_view(url='/2023/program/schedule/', permanent=True)),

                path("pattern-lib/", TemplateView.as_view(template_name='pages/pattern_lib.html'), name='pattern_lib'),

                path("admin/", admin.site.urls),
                path("wt/", include("wagtail.admin.urls")),
                path("team/", include("team.urls")),
                path("sponsors/", include("sponsors.urls")),
                path("announcements/", include("announcements.urls")),
                path("program/", include("program.urls")),
                path("intermissions/", include("intermissions.urls")),
                path("", include("wagtail.urls")),
            ]
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += [path("", RedirectView.as_view(url="/2023/"))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

program/views.py
import datetime
import re

from django.db.models import Prefetch
from django.http import Http404, HttpRequest, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import render_to_string
from django.template.response import HttpResponse, TemplateResponse
from django.utils import timezone

from program.models import Slot, Speaker, Talk, Workshop
from program.schedule_grid import ScheduleGrid

# Note: conference days are currently hardcoded.
# We could build the list directly from the database to make the code more
# re-usable for the next year, but right now it seems like an overkill.
CONFERENCE_DAYS = {
    "friday": datetime.date(2023, 9, 15),
    "saturday": datetime.date(2023, 9, 16),
    "sunday": datetime.date(2023, 9, 17),
}


def session_detail(request, type, session_id: int):
    model_map = dict(talk=Talk, panel=Talk, workshop=Workshop, sprint=Workshop)
    session = get_object_or_404(
        model_map.get(type), id=session_id, is_public=True, is_backup=False
    )

    # Database allows adding a session to multiple slots.
    # First slot is the talk itself, other slots are for streaming to other rooms.
    session_slot = session.slot_set.order_by("start", "room__order").first()

    session_previous = (
        model_map.get(type)
        .objects.filter(is_public=True, is_backup=False, order__lt=session.order)
        .order_by("order")
        .last()
    )

    if not session_previous:  # at the first session provide the last one as previous
        session_previous = (
            model_map.get(type)
            .objects.filter(is_public=True, is_backup=False)
            .order_by("order")
            .last()
        )

    session_next = (
        model_map.get(type)
        .objects.filter(is_public=True, is_backup=False, order__gt=session.order)
        .order_by("order")
        .first()
    )

    if not session_next:  # at the last session provide the first one as next
        session_next = (
            model_map.get(type)
            .objects.filter(is_public=True, is_backup=False)
            .order_by("order")
            .first()
        )

    schedule_grid = None
    current_day = None

    if session_slot:
        for day, day_date in CONFERENCE_DAYS.items():
            if day_date == session_slot.start.date():
                current_day = day
                break

        schedule_slots = (
            Slot.objects.filter(
                start__gte=session_slot.start - datetime.timedelta(hours=1),
                start__lte=session_slot.start + datetime.timedelta(hours=1),
            )
            .select_related(
                "room",
            )
            .prefetch_related(
                "talk",
                Prefetch(
                    "talk__talk_speakers",
                    queryset=Speaker.objects.filter(is_public=True),
                    to_attr="public_speakers",
                ),
                "workshop",
                Prefetch(
                    "workshop__workshop_speakers",
                    queryset=Speaker.objects.filter(is_public=True),
                    to_attr="public_speakers",
                ),
                "utility",
            )
            .order_by(
                "start",
                "room__order",
            )
        )

        schedule_grid = ScheduleGrid.create_from_slots(schedule_slots)
        # Remove leading grid rows that contains only breaks and other
        # non-streamed utilities
        while schedule_grid.rows[0].contains_only_non_streamed_utilities():
            schedule_grid.pop_row(0)

    return TemplateResponse(
        request,
        template="program/{}_detail.html".format(type),
        context={
            "session": session,
            "other_sessions": {
                "previous": session_previous,
                "next": session_next,
            },
            "session_slot": session_slot,
            "schedule_grid": schedule_grid,
            "current_day": current_day,
        },
    )


def talks_list(request):
    talks = Talk.objects.filter(is_backup=False)
    public_talks = talks.filter(is_public=True).order_by("order")
    more_to_come = talks.filter(is_public=False).exists()

    return TemplateResponse(
        request,
        template="program/talks_list.html",
        context={"sessions": public_talks, "more_to_come": more_to_come},
    )


def workshops_list(request):
    workshops = Workshop.objects.filter(is_backup=False)
    public_workshops = workshops.filter(is_public=True).order_by("order")
    more_to_come = workshops.filter(is_public=False).exists()

    return TemplateResponse(
        request,
        template="program/workshops_list.html",
        context={"sessions": public_workshops, "more_to_come": more_to_come},
    )


def schedule_redirect(request) -> HttpResponse:
    # Gets time in the local timezone (Europe/Prague, as set in settings.py).
    today = timezone.localdate()
    selected_day = None
    for conference_day, date_value in CONFERENCE_DAYS.items():
        # Redirect to first day by default
        if selected_day is None:
            selected_day = conference_day
        if date_value == today:
            selected_day = conference_day
            break

    response = redirect(
        to="program:schedule_day",
        conference_day=selected_day,
        permanent=False,
    )
    # Add a caching header to make sure it is not stored in any cache.
    response.headers["Cache-Control"] = "no-store"
    return response


def schedule_day(request: HttpRequest, conference_day: str) -> HttpResponse:
    try:
        schedule_date = CONFERENCE_DAYS[conference_day]
    except KeyError:
        raise Http404()

    slots = (
        Slot.objects.filter(start__date=schedule_date)
        .select_related("room")
        .prefetch_related(
            "talk",
            Prefetch(
                "talk__talk_speakers",
                queryset=Speaker.objects.filter(is_public=True),
                to_attr="public_speakers",
            ),
            "workshop",
            Prefetch(
                "workshop__workshop_speakers",
                queryset=Speaker.objects.filter(is_public=True),
                to_attr="public_speakers",
            ),
            "utility",
        )
        .order_by(
            "start",
            "room__order",
        )
    )

    schedule_grid = ScheduleGrid.create_from_slots(slots)

    return TemplateResponse(
        request,
        template="program/schedule_day.html",
        context={
            "schedule_date": schedule_date,
            "slots": slots,
            "all_days": CONFERENCE_DAYS,
            "current_day": conference_day,
            "grid": schedule_grid,
        },
    )


def schedule_json(request):
    all_slots = (
        Slot.objects.select_related("room")
        .prefetch_related(
            "talk",
            Prefetch(
                "talk__talk_speakers",
                queryset=Speaker.objects.filter(is_public=True),
                to_attr="public_speakers",
            ),
            "workshop",
            Prefetch(
                "workshop__workshop_speakers",
                queryset=Speaker.objects.filter(is_public=True),
                to_attr="public_speakers",
            ),
            "utility",
        )
        .order_by(
            "start",
            "room__order",
        )
    )

    schedule_grid = ScheduleGrid.create_from_slots(all_slots)
    result = []
    for row in schedule_grid.rows:
        for item in row.items:
            session = item.slot.event
            session_json = {
                "title": session.title,
            }
            if isinstance(session, (Talk, Workshop)):
                session_json.update(
                    {
                        "type": session.type,
                        "abstract": session.abstract,
                        "track": session.track,
                        "language": session.language,
                        "minimum_python_knowledge": session.minimum_python_knowledge,
                        "minimum_topic_knowledge": session.minimum_topic_knowledge,
                        "speakers": [
                            {
                                "name": speaker.full_name,
                                "twitter": speaker.twitter if speaker.twitter else None,
                                "github": speaker.github if speaker.github else None,
                                "linkedin": speaker.linkedin
                                if speaker.linkedin
                                else None,
                                "personal_website": speaker.personal_website
                                if speaker.personal_website
                                else None,
                            }
                            for speaker in session.speakers
                        ],
                    }
                )
            else:
                session_json["type"] = "other"

            slot_json = {
                "start": item.slot.start.isoformat(),
                "end": item.slot.end.isoformat(),
                "room": item.slot.room.label,
                "is_streamed": item.is_streamed,
                "session": session_json,
            }
            result.append(slot_json)

    return JsonResponse(
        {
            "schedule": result,
        }
    )


def debug_og_image_for_talk(request, session_id: int) -> HttpResponse:
    """
    DEBUG view: preview OG image template for a talk.
    """
    talk = get_object_or_404(Talk, pk=session_id)
    return _render_og_template(
        request,
        template="program/og_images/talk.html",
        context={"session": talk},
    )


def debug_og_image_for_workshop(request, session_id: int) -> HttpResponse:
    """
    DEBUG view: preview OG image template for a workshop.
    """
    workshop = get_object_or_404(Workshop, pk=session_id)

templates/program/__day_menu.html
{% for day, date in all_days.items %}
    <a
            href="{% url "program:schedule_day" day %}"
            class="btn {% if day == current_day %}btn-secondary{% else %}btn-light{% endif %}"
    >
        {{ date|date:"l j F" }}
    </a>
{% endfor %}

templates/program/__schedule-grid.html
{% load markdown static %}
<div class="PC-schedule PC-schedule-{{ current_day }}">
    {% for row in grid.rows %}
        {% for item in row.items %}
            <div class="PC-schedule-item PC-schedule-item-type-{{ item.type }}"
                 style="grid-area: {{ item.grid_area }}">

                <div class="PC-schedule-timeplace">
                    {{ row.time|date:"G:i" }}
                    {% if not item.is_multi_room or item.is_streamed %}
                        <b>{{ item.slot.room.label }}</b>
                    {% endif %}
                </div>

                <div class="PC-schedule-session {% if item.slot == current_slot %}PC-schedule-session-active{% endif %}">

                    <h3 class="PC-schedule-item-title pe-4">
                        {% if item.slot.event.get_absolute_url %}
                            <a class="stretched-link {% if item.type == 'utility' %}link-light{% endif %}"
                               href="{{ item.slot.event.get_absolute_url }}">
                                {{ item.slot.event }}
                            </a>
                        {% else %}
                            {{ item.slot.event }}
                        {% endif %}
                    </h3>

                    {% if item.slot.event.description %}
                        <div class="PC-schedule-description">
                            {{ item.slot.event.description|markdown }}
                        </div>
                    {% endif %}


                    {% if item.slot.event.speakers %}
                        <div class="PC-schedule-item-speakers">
                            <div class="mb-1
                                {% if item.slot.event.speakers|length > 1 %}
                                    d-flex
                                {% else %}
                                    d-inline-flex me-2
                                {% endif %}
                                ">
                                {% for speaker in item.slot.event.speakers %}
                                    <div class="PC-schedule-photo">
                                        <div class="position-relative">
                                            <div class="PC-image-primary">
                                                <img class="img-fluid" src="{{ speaker.photo.url }}" width="48" height="48" alt="">
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            {% for speaker in item.slot.event.speakers %}{% if forloop.last and not forloop.first %} <span class="d-inline-block">&amp; {% elif not forloop.first %},</span> <span class="d-inline-block">{% endif %}{% spaceless %}{{ speaker.full_name }}{% if forloop.last %}</span>{% endif %}{% endspaceless %}{% endfor %}
                        </div>
                    {% endif %}
                    {% if item.is_streamed %}
                        <div class="{% if not item.slot.event.speakers %}mt-3{% endif %}">
                            streamed to other rooms
                        </div>
                    {% endif %}


                    <div class="PC-language PC-language-sessions d-flex flex-column gap-2">
                        {% if item.slot.event.track == 'beginners' %}
                            <img
                                    src="{% static 'img/icons/beginner.min.svg' %}"
                                    width="24" height="24"
                                    alt="Beginner’s track"
                                    class=""
                            >
                        {% endif %}
                        {% if item.slot.event.track == 'pydata' %}
                            <img
                                    src="{% static 'img/icons/pydata.min.svg' %}"
                                    width="24" height="24"
                                    alt="PyData track"
                                    class=""
                            >
                        {% endif %}
                        {% if item.slot.event.language == 'cs' %}
                            <img
                                    src="{% static 'img/flag-cz.svg' %}"
                                    width="24" height="24"
                                    alt="only in Czech"
                                    class=""
                            >
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endfor %}
</div>

templates/program/__session.html
{% load markdown %}
{% load static %}


<article class="
        PC-sessions-session
        PC-sessions-session-l-{{ session.speakers|length }}
        shadow rounded border border-black border-2
        position-relative
    ">
    <div class="PC-sessions-photos rounded-top">

        {% for speaker in session.speakers %}
            <div class="PC-sessions-photo">
                <div class="position-relative">
                    <div class="PC-image-primary">
                        <img class="img-fluid" src="{{ speaker.photo.url }}" width="300" height="300" alt="">
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="PC-sessions-text p-3">
        <h3 class="h5 mt-0">
            <a class="stretched-link" href="{% url 'program:session_detail' type=session.type session_id=session.id %}">
                {{ session.title }}
            </a>
        </h3>
        <p>
            {% for speaker in session.speakers %}
                <span class="d-inline-block">{{ speaker.full_name }}</span>{% if forloop.revcounter0 %},{% endif %}
            {% endfor %}
        </p>
        {% if session.language == 'cs' %}
            <div class="PC-language PC-language-sessions">
                <img
                        src="{% static 'img/flag-cz.svg' %}"
                        width="32" height="32"
                        alt=""
                        class=""
                >
                <span class="fs-6 PC-language-label">in Czech only</span>
            </div>
        {% endif %}
        {% comment %}{{ session.title|length }}{% endcomment %}
        {% comment %}order:                    {{ session.order|pprint }}{% endcomment %}
        {% comment %}minimum_python_knowledge: {{ session.minimum_python_knowledge|pprint }}{% endcomment %}
        {% comment %}minimum_topic_knowledge:  {{ session.minimum_topic_knowledge|pprint }}{% endcomment %}
        {% comment %}{{ session.abstract|render_markdown }}{% endcomment %}
    </div>
    {% comment %}<a {% block detail_link %} href="{% url 'session_detail' type=session.type session_id=session.id %}#main" {% endblock %}></a>{% endcomment %}
</article>

templates/program/__speaker_detail.html
{% load markdown %}
{% load static %}
{% load regex %}

<article class="PC-speaker border border-black shadow mb-5 border-2 rounded">
    <div class="row g-0">
        <div class="col-12 col-md-6 col-lg-5 px-0 position-relative">
            <div class="PC-image-primary PC-image-cover">
                <img class="img-fluid" src="{{ speaker.photo.url }}" width="400" height="400" alt="">
            </div>
        </div>
        <div class="col px-3 px-xxs-4 px-sm-5 pb-xs-4 pt-2 pt-xl-3">
            <h3 class="h1 mt-3 mt-sm-4">{{ speaker.full_name }}</h3>
            {% if speaker.github or speaker.twitter or speaker.linkedin or speaker.personal_website %}
                <ul class="list-inline font-monospace">
                    {% if speaker.github %}
                        <li class="list-inline-item">
                            <a href="{{ speaker.github }}">
                                <i class="bi-github link-primary me-2"></i>{{ speaker.github|regexextract:'.+/(.+?)/?$' }}
                            </a>
                        </li>
                    {% endif %}
                    {% if speaker.twitter %}
                        <li class="list-inline-item">
                            <a href="{{ speaker.twitter }}">
                                <i class="bi-twitter link-primary me-2"></i>{{ speaker.twitter|regexextract:'.+/(.+?)/?$' }}
                            </a>
                        </li>
                    {% endif %}
                    {% if speaker.linkedin %}
                        <li class="list-inline-item">
                            <a href="{{ speaker.linkedin }}">
                                <i class="bi-linkedin link-primary me-2"></i>LinkedIn
                            </a>
                        </li>
                    {% endif %}
                    {% if speaker.personal_website %}
                        <li class="list-inline-item">
                            <a href="{{ speaker.personal_website }}">
                                <i class="bi-globe link-primary me-2"></i>{{ speaker.personal_website|regexextract:'^(?:https?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:\/\n?]+)' }}
                            </a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
            {{ speaker.bio|markdown }}
            {% if user.is_staff %}
                <p>
                    <a class="btn btn-danger" href="https://pretalx.com/orga/event/pycon-cz-23/speakers/{{ speaker.pretalx_code }}">
                        Edit speaker in preTALX
                    </a>
                    <i>you see this because you’re logged in as administrator</i>
                </p>
            {% endif %}
        </div>
    </div>
</article>

{% comment %}

<div class="bg-secondary-subtle">

    {% if type == 'keynoter' or type == 'intermission' %}
        {% with talk=speaker.talks.all|first %}
            <p>
                <a
                        {% if type == 'keynoter' %} {% elif type == 'intermission' %} {% endif %}
                        href="{% url 'program:session_detail' type='talk' session_id=talk.id %}"
                >
                    {{ talk.title }}
                </a>
            </p>
        {% endwith %}
    {% endif %}

    {% if session %}{# checks if this is included in session detail #}
        {# todo: refactor: this should get cleaner data from Python, too much logic here #}
        {# todo: with it we could also do a nicer listing of more than one other session #}

        {% with talks=speaker.talks.all workshops=speaker.workshops.all %}
            {% if session.type == 'talk' %}
                {% with extra_talks=talks|length|add:-1 extra_workshops=workshops|length %}
                    {% if extra_talks %}
                        <p>
                            Check my other {{ extra_talks|pluralize:'talk,talks' }}
                            {% for talk in talks %}
                                {% if talk.id != session.id %}
                                    <a class="{{ extra_talks|pluralize:',d-block' }}" href="{% url 'program:session_detail' type=talk.type session_id=talk.id %}">{{ talk.title }}</a>
                                {% endif %}
                            {% endfor %}
                        </p>
                    {% endif %}
                    {% if extra_workshops %}
                        <p>
                            I also lead
                            {% for workshop in workshops %}
                                <span>
                                            a&nbsp;{{ workshop.type }}
                                            <a href="{% url 'program:session_detail' type=workshop.type session_id=workshop.id %}">{{ workshop.title }}</a>
                                        </span>
                            {% endfor %}
                        </p>
                    {% endif %}
                {% endwith %}
            {% elif session.type == 'workshop' or session.type == 'sprint' %}
                {% with extra_talks=talks|length extra_workshops=workshops|length|add:-1 %}
                    {% if extra_workshops %}
                        <p>
                            I also lead
                            {% for workshop in workshops %}
                                {% if workshop.id != session.id %}
                                    <span>
                                            a&nbsp;{{ workshop.type }}
                                            <a href="{% url 'program:session_detail' type=workshop.type session_id=workshop.id %}">{{ workshop.title }}</a>
                                        </span>
                                {% endif %}
                            {% endfor %}
                        </p>
                    {% endif %}
                    {% if extra_talks %}
                        <p>
                            Check my {{ extra_talks|pluralize:'talk,talks' }}
                            {% for talk in talks %}
                                <a href="{% url 'program:session_detail' type=talk.type session_id=talk.id %}">
                                    {{ talk.title }}
                                </a>
                            {% endfor %}
                        </p>
                    {% endif %}
                {% endwith %}
            {% endif %}
        {% endwith %}
    {% endif %}
</div>
{% endcomment %}

templates/program/panel_detail.html
{% extends 'program/_session_detail.html' %}

templates/program/schedule_day.html
{% extends '_layout.html' %}


{% load static %}


{% block meta_title %}Schedule: {{ schedule_date|date:"l j F" }} – {{ block.super }}{% endblock %}


{% block header-bg-class %}{% endblock %}


{% block body_extras %}class="PC-bg-header PC-bg-header-extra"{% endblock %}


{% block main %}
    <div class="text-white">
        <div class="container-xs pb-6">
            <h1>Schedule</h1>

            <div class="d-sm-none pt-2 mb-2">
                <div class="btn-group-vertical">
                    {% include 'program/__day_menu.html' %}
                </div>
            </div>

            <div class="d-none d-sm-block sticky-md-top pt-2 mb-4">
                <div class="btn-group">
                    {% include 'program/__day_menu.html' %}
                </div>
            </div>

            {% if current_day == 'sunday' %}
                <p class="lead mb-2">
                    Workshop day at FIT ČVUT
                </p>
                <ul class="mb-5">
                    <li>Workshop’s capacity is limited</li>
                    <li>Registration will open on Tuesday 12 September at 15:00</li>
                    <li>Workshops might be shorter than 3-hour slot they have available</li>
                </ul>
            {% else %}
                <p class="lead mb-4">Talk day at Gabriel Loci</p>
            {% endif %}

            {% include 'program/__schedule-grid.html' %}
        </div>
    </div>
{% endblock %}

templates/program/sprint_detail.html
{% extends 'program/_session_detail.html' %}

templates/program/talk_detail.html
{% extends 'program/_session_detail.html' %}

templates/program/talks_list.html
{% extends 'program/_base_list.html' %}


{% load markdown %}


{% block meta_title %}Talks – {{ block.super }}{% endblock %}


{% block speakers_title %}Talks{% endblock %}

{% block top_info %}
    <p class="lead">Talks will happen on Friday and Saturday at <a href="{% url 'venue' %}#gabriel-loci">Gabriel Loci</a>.</p>

    {{ block.super }}

{% endblock %}
{% comment %}
{% block top_info %}
    {% if sessions and phases.talks != 'not_public' %}
        {{ block.super }}
        {% if phases.talks == 'list_public' %}
            <p class="lead">We will publish more information about talks and speakers soon.</p>
        {% endif %}
    {% else %}
        <p class="lead">No talks have been published yet. Please check again later.</p>
    {% endif %}
{% endblock %}


{% block detail_link %}
    {% if phases.talks == 'details_public' %}
        {{ block.super }}
    {% endif %}
{% endblock %}

{% endcomment %}


{% block more_sessions_name %}talks{% endblock %}


{% block other_sessions %}
    {% url 'program:workshops_list' as other_session_url %}
    {% with other_session_name='workshops' %}
        {{ block.super }}
    {% endwith %}
    {% if phases.workshops != 'not_published' %}{% endif %}
{% endblock %}

templates/program/workshop_detail.html
{% extends 'program/_session_detail.html' %}