sponsors/urls.py
from django.urls import re_path

from sponsors.views import sponsors_list

urlpatterns = [
    re_path("^$", sponsors_list, name="sponsors_list"),
]

urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path(
        "2023/",
        include(
            [
                path("", TemplateView.as_view(template_name='pages/homepage.html'), name='homepage'),
                path("coc/", TemplateView.as_view(template_name='pages/coc.html'), name='coc'),
                path("privacy-policy/", TemplateView.as_view(template_name='pages/privacy_policy.html'), name='privacy_policy'),
                path("cfp/", TemplateView.as_view(template_name='pages/cfp.html'), name='cfp'),
                path("cfp-guide/", TemplateView.as_view(template_name='pages/cfp_guide.html'), name='cfp_guide'),
                path("cfp-pruvodce/", TemplateView.as_view(template_name='pages/cfp_pruvodce.html'), name='cfp_pruvodce'),
                path("sponsorship/", TemplateView.as_view(template_name='pages/sponsorship.html'), name='sponsorship'),
                # Original view for tickets: TemplateView.as_view(template_name='pages/tickets.html')
                path("tickets/", RedirectView.as_view(pattern_name="homepage"), name='tickets'),
                path("financial-aid/", TemplateView.as_view(template_name='pages/financial-aid.html'), name='financial_aid'),
                path("financial-aid-grantees/", TemplateView.as_view(template_name='pages/financial-aid-grantees.html'), name='financial_aid_grantees'),
                path("venue/", TemplateView.as_view(template_name='pages/venue.html'), name='venue'),
                path("board-game-night/", TemplateView.as_view(template_name='pages/board-game-night.html'), name='board_game_night'),
                path("prague/", TemplateView.as_view(template_name='pages/prague.html'), name='prague'),

                path("pyconcz-discord/", RedirectView.as_view(url='https://discord.gg/UtPkpPB7te', permanent=True)),
                path("discord/", RedirectView.as_view(url='https://discord.gg/UtPkpPB7te', permanent=True)),
                path("3D/", RedirectView.as_view(url='https://docs.google.com/forms/d/e/1FAIpQLSeyr13vobeJVqBgucq27j0yLzbH6tTmSYP4dZEDLEkCYHI6Hg/viewform', permanent=True)),
                path("tshirt/", RedirectView.as_view(url='https://pretix.eu/pyconcz/pyconcz23/redeem?voucher=TSHIRT', permanent=False)),
                path("schedule/", RedirectView.as_view(url='/2023/program/schedule/', permanent=True)),

                path("pattern-lib/", TemplateView.as_view(template_name='pages/pattern_lib.html'), name='pattern_lib'),

                path("admin/", admin.site.urls),
                path("wt/", include("wagtail.admin.urls")),
                path("team/", include("team.urls")),
                path("sponsors/", include("sponsors.urls")),
                path("announcements/", include("announcements.urls")),
                path("program/", include("program.urls")),
                path("intermissions/", include("intermissions.urls")),
                path("", include("wagtail.urls")),
            ]
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += [path("", RedirectView.as_view(url="/2023/"))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sponsors/models.py
from django.db import models
from django.utils.text import slugify
from wagtail.models import Page


class Level(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=False, blank=True)
    order = models.PositiveIntegerField(help_text="display order on front end (lower the number, the higher it is)")
    size = models.PositiveIntegerField(default=0, help_text="visual size (lower the number, the bigger it is)")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Level, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['order', 'title']


class Sponsor(models.Model):
    level = models.ForeignKey(Level, on_delete=models.SET_NULL, null=True)

    name = models.CharField(max_length=200, unique=True)
    logo = models.FileField(null=True, blank=True, help_text="SVG only", upload_to="sponsors/")

    description = models.TextField(
        null=True, blank=True, help_text="markdown formatted"
    )
    link_url = models.URLField()
    twitter = models.URLField(null=True, blank=True, help_text="full URL")
    facebook = models.URLField(null=True, blank=True, help_text="full URL")
    linkedin = models.URLField(null=True, blank=True, help_text="full URL")

    published = models.BooleanField(default=False)

    class Meta:
        ordering = ["level", "name"]

    def __str__(self):
        return self.name

    @property
    def slug(self):
        return slugify(self.name)

sponsors/views.py
from django.template.response import TemplateResponse

from sponsors.models import Sponsor


def sponsors_list(request):
    sponsors = Sponsor.objects.filter(published=True)
    return TemplateResponse(
        request, "sponsors/sponsors_list.html", {"sponsors_list": sponsors}
    )

templates/sponsors/sponsors_homepage.html
{% load sponsors_tags %}

{% get_sponsors as sponsors %}

{% regroup sponsors by get_level_display as sponsors_list %}

{% if sponsors %}
    <section class="pc-sponsors">
        {% for level in sponsors_list %}
            <h2 class="h3 mb-5 text-center {% if forloop.first %}mt-2{% endif %}">{{ level.grouper }}</h2>
            <div class="pc-sponsors-list">
                {% for sponsor in level.list %}
                    <a href="{{ sponsor.link_url }}"
                       class="pc-sponsors-item pc-sponsors-item-{{ level.grouper|lower }}"
                    >
                        {% if sponsor.logo %}
                            <img class="img-fluid pc-img-fluid-svg" src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}">
                        {% else %}
                            {{ sponsor.name }}
                        {% endif %}
                    </a>
                {% endfor %}
            </div>
        {% endfor %}
    </section>
{% endif %}

templates/sponsors/sponsors_list.html
{% extends '_layout.html' %}

{% load markdown %}
{% load regex %}


{% block meta_title %}Sponsors and partners – {{ block.super }}{% endblock %}


{% block main_classes %}bg-white text-dark{% endblock %}


{% block main %}
    <div class="container-xs pt-4 pb-3 mt-3">
        {% comment %}{% if phases.sponsors != 'details_public' and not user.is_staff %}
            <h1>404 Not Found</h1>
            <p>Sorry, this page is not available, please <a href="/">go to homepage</a>.</p>
        {% else %}{% endcomment %}

        {% regroup sponsors_list by level as sponsor_levels %}


        <h1>Sponsors and partners</h1>

        {% comment %}{% if phases.sponsors != 'details_public' %}
                <div class="alert alert-warning h2 my-5">
                    ⚠️ You see sponsors on this page because you’re logged in.
                    <br>Publicly they’re hidden.
                </div>
            {% endif %}{% endcomment %}

        <div class="row">
            <div class="col-sm col-md-6">
                <p class="lead">We’re grateful to companies that help us organize PyCon CZ and allow keeping ticket prices as low as&nbsp;possible.</p>
            </div>
            <div class="col-sm col-md">
                <p>
                    Do you want to sponsor us too?
                    <br>Check out <a href="{% url 'sponsorship' %}">sponsorship options</a>.
                </p>
            </div>
        </div>

        {% for level in sponsor_levels %}
            <section class="PC-sponsor-detail" id="{{ level.list.0.level.slug }}">
                <h2 class="mt-md-6">{{ level.grouper }}</h2>
                {% for sponsor in level.list %}
                    <div
                            class="row {% if not sponsor.description %}align-items-center mt-4 mb-5{% endif %}"
                            id="sponsor-{{ sponsor.slug }}"
                    >
                        <div class="col-12 col-sm-8 col-md-4 col-lg-3 mt-5 mt-sm-4 {% if not sponsor.description %}mb-3 mb-sm-4{% endif %}">
                            {% if sponsor.logo %}
                                <a href="{{ sponsor.link_url }}" class="d-block">
                                    <img
                                            class="PC-sponsor-detail-logo img-fluid PC-img-fluid-svg"
                                            src="{{ sponsor.logo.url }}"
                                            alt="{{ sponsor.name }}"
                                    >
                                </a>
                            {% endif %}
                        </div>

                        <div class="col-12 col-md mt-sm-2 mb-sm-4">
                            <h3 class="PC-sponsor-detail-heading {% if not sponsor.description %}d-none d-md-block{% endif %}">
                                <a href="{{ sponsor.link_url }}">{{ sponsor.name }}</a>
                            </h3>
                            {% if sponsor.description %}

                                {% if sponsor.twitter or sponsor.linkedin or sponsor.facebook %}
                                    <ul class="list-inline font-monospace">
                                        {% if sponsor.twitter %}
                                            <li class="list-inline-item">
                                                <a href="{{ sponsor.twitter }}">
                                                    <i class="bi-twitter link-primary me-2"></i>{{ sponsor.twitter|regexextract:'.+/(.+?)/?$' }}
                                                </a>
                                            </li>
                                        {% endif %}
                                        {% if sponsor.linkedin %}
                                            <li class="list-inline-item">
                                                <a href="{{ sponsor.linkedin }}">
                                                    <i class="bi-linkedin link-primary me-2"></i>LinkedIn
                                                </a>
                                            </li>
                                        {% endif %}
                                        {% if sponsor.facebook %}
                                            <li class="list-inline-item">
                                                <a href="{{ sponsor.facebook }}">
                                                    <i class="bi-facebook link-primary me-2"></i>{{ sponsor.facebook|regexextract:'.+/(.+?)/?$' }}
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                {% endif %}

                                <div class="PC-sponsor-detail-description">
                                    {{ sponsor.description|markdown }}
                                </div>

                                {% if user.is_staff and sponsor.description %}
                                    <div class="alert alert-info">
                                        ℹ️ {{ sponsor.description|markdown|striptags|wordcount }} words <i>you see this because you’re logged in as administrator</i>
                                    </div>
                                {% endif %}

                            {% endif %}
                        </div>

                    </div>
                {% endfor %}
            </section>
        {% endfor %}
        {% comment %}{% endif %}{% endcomment %}
    </div>
{% endblock %}